[package]
name = "gb2fasta"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
gb-io = "0.7.1"
clap = {version = "3.0", features = ["derive"] }
flate2 = "1.0"